version: "3"
services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/supermarket
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    restart: always
    links:
      - php-fpm
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - proxy

  php-fpm:
    build:
      context: docker/php
    restart: always
    volumes:
      - ./:/var/www/supermarket
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - proxy
      - db

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: simple
    ports:
      - "9999:3306"
    networks:
      db:

networks:
  db:
  proxy:
